dashboard:
  id: SO0122-DHTv1_2_0_Dashboard
  name: SO0122-DHTv1_2_0_Dashboard
analysis:
  id: SO0122-DHTv1_2_0_Analysis
  name: SO0122-DHTv1_2_0_Analysis
dataset:
  image-text:
    id: SO0122-v1_1_0-img-text-dataset
    name: SO0122-v1.1-img-text-dataset
  sentiment:
    id: SO0122-v1_1_0-sentiment-dataset
    name: SO0122-v1.1.0-sentiment-dataset
  text:
    id: SO0122-v1_1_0-text-dataset
    name: SO0122-v1.1-text-dataset
  topic:
    id: SO0122-v1_1_0-topic-dataset
    name: SO0122-v1.1-topic-dataset
datasource:
  id: SO0122-v1_1_0_DataSource
  name: SO0122-v1_1_0_DataSource
